"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os

from pathlib import Path


# BASE DEL PROYECTO

BASE_DIR = Path(__file__).resolve().parent.parent


# SEGURIDAD

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only'
)


DEBUG = os.environ.get(
    'DJANGO_DEBUG',
    'True'
).lower() == 'true'


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]


# Permite agregar el dominio del servidor
# mediante una variable de entorno.

DJANGO_ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS'
)

if DJANGO_ALLOWED_HOSTS:

    ALLOWED_HOSTS.extend(
        DJANGO_ALLOWED_HOSTS.split(',')
    )


# APLICACIONES

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
]


# MIDDLEWARE

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# URLS

ROOT_URLCONF = 'config.urls'


# TEMPLATES

TEMPLATES = [
    {
        'BACKEND': (
            'django.template.backends.django.DjangoTemplates'
        ),

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        },
    },
]


# WSGI

WSGI_APPLICATION = 'config.wsgi.application'


# BASE DE DATOS

DATABASES = {

    'default': {

        'ENGINE': (
            'django.db.backends.sqlite3'
        ),

        'NAME': (
            BASE_DIR / 'db.sqlite3'
        ),

    }

}


# VALIDACIÓN DE CONTRASEÑAS

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },

    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },

]


# IDIOMA Y ZONA HORARIA

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Montevideo'

USE_I18N = True

USE_TZ = True


# ARCHIVOS ESTÁTICOS

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'


# ARCHIVOS SUBIDOS

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# EMAIL

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)